# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelicense',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usagelicense',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
