# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-30 12:04
from __future__ import unicode_literals

from django.db import migrations

try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields.jsonb import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180807_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelicense',
            name='extra',
            field=JSONField(blank=True, default=dict),
        ),
    ]
