# Generated by Django 4.0.4 on 2023-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181031_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelicense',
            name='last_synced_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last sync'),
        ),
    ]
