# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('langcode', models.CharField(blank=True, default='en-us', max_length=12, verbose_name='language')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AlterUniqueTogether(
            name='placeholder',
            unique_together=set([('name', 'langcode')]),
        ),
    ]
